contact_links:
  - name: I have a question 🤔
    url: https://github.com/AppSolves/pylocalauth/discussions
    about: If you have any question about the usage of pylocalauth that's not clearly a bug, please open a discussion first.
